/* Nicola Rennie's upstream catalogue is regenerated by her repository workflow. */
(function(root) {
  const RAW = 'https://raw.githubusercontent.com/nrennie/tidytuesday/main/';
  const URL = RAW + 'data/all_weeks.csv';
  function path(value) {
    const clean = String(value || '').replace(/\/{2,}/g, '/');
    if (!/^\d{4}\/[\d-]+\/.+/.test(clean) || /[?#\\]/.test(clean) || clean.split('/').some(x => x === '.' || x === '..')) throw Error('Invalid catalogue path');
    return clean.split('/').map(encodeURIComponent).join('/');
  }
  function parse(csv, papa) {
    const result = papa.parse(csv, {header:true, skipEmptyLines:'greedy'});
    if (result.errors.length || !result.meta.fields?.includes('img_fpath')) throw Error('Invalid catalogue');
    const rows = result.data.map(x => {
      let d = x.week;
      if (/^\d{2}-\d{2}-\d{4}$/.test(d)) d = d.split('-').reverse().join('-');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(d) || !Number.isFinite(Date.parse(d)) || new Date(d).toISOString().slice(0,10) !== d) throw Error('Invalid plot');
      const i = path(x.img_fpath), c = path(x.code_fpath);
      return {d, y:d.slice(0,4), t:x.title?.trim() || `TidyTuesday · ${d}`, i:RAW+i, c:RAW+c,
        g:'https://github.com/nrennie/tidytuesday/tree/main/'+c.slice(0,c.lastIndexOf('/')),
        l:c.endsWith('.svelte') ? 'Svelte' : x.code_type || 'Other', p:x.pkgs || ''};
    });
    if (!rows.length) throw Error('Empty catalogue');
    return rows;
  }
  function merge(previous, incoming) {
    const rows = new Map(previous.map(x => [x.d,x]));
    incoming.forEach(x => rows.set(x.d,x));
    return [...rows.values()].sort((a,b) => b.d.localeCompare(a.d));
  }
  function filter(rows, year, language, query) {
    const words = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
    return rows.filter(x => (year === 'all' || x.y === year) && (language === 'all' || x.l === language) && words.every(w => `${x.t} ${x.d} ${x.l} ${x.p || ''}`.toLocaleLowerCase().includes(w)));
  }
  const api = {URL, parse, merge, filter};
  if (typeof module !== 'undefined') module.exports = api;
  else root.GalleryCatalog = api;
})(globalThis);
