window.GALLERY_SNAPSHOT = [
 {
  "d": "2025-30-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 30,
  "t": "Makeover",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_30.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_30.R",
  "l": "R",
  "p": "metR, tidyverse, camcorder, sf, showtext, elevatr, MetBrewer, ggtext, glue, nrBrand, terra",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_30.R"
 },
 {
  "d": "2025-29-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 29,
  "t": "Raster",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_29.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_29.R",
  "l": "R",
  "p": "tidyverse, ggtext, nrBrand, rnaturalearth, showtext, terra, elevatr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_29.R"
 },
 {
  "d": "2025-28-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 28,
  "t": "Black",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_28.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_28.R",
  "l": "R",
  "p": "tidyverse, sf, showtext, ggtext, nrBrand, glue, rnaturalearth, ggfx",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_28.R"
 },
 {
  "d": "2025-27-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 27,
  "t": "Boundaries",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_27.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_27.R",
  "l": "R",
  "p": "tidyverse, sf, showtext, ggtext, nrBrand, camcorder, glue",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_27.R"
 },
 {
  "d": "2025-26-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 26,
  "t": "Transport",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_26.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_26.R",
  "l": "R",
  "p": "openrouteservice, tidyverse, osmdata, sf, showtext, nrBrand, ggtext, MetBrewer, camcorder, dplyr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_26.R"
 },
 {
  "d": "2025-25-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 25,
  "t": "Hexagons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_25.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_25.R",
  "l": "R",
  "p": "ggplot2, dplyr, stringr, showtext, nrBrand, ggtext, geofacet, camcorder, glue, tibble, PrettyCols",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_25.R"
 },
 {
  "d": "2025-24-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 24,
  "t": "Places and their names",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_24.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_24.R",
  "l": "R",
  "p": "tidyverse, sf, showtext, ggtext, nrBrand, camcorder, glue, MetBrewer",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_24.R"
 },
 {
  "d": "2025-23-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 23,
  "t": "Process",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_23.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_23.R",
  "l": "R",
  "p": "camcorder",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_23.R"
 },
 {
  "d": "2025-22-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 22,
  "t": "Natural Earth",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_22.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_22.R",
  "l": "R",
  "p": "geodata, ggplot2, dplyr, biscale, elevatr, sf, showtext, nrBrand, ggtext, cowplot",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_22.R"
 },
 {
  "d": "2025-21-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 21,
  "t": "Icons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_21.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_21.R",
  "l": "R",
  "p": "gapminder, geofacet, tidyverse, ggforce, camcorder, glue, nrBrand, ggtext, scales, showtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_21.R"
 },
 {
  "d": "2025-20-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 20,
  "t": "Water",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_20.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_20.R",
  "l": "R",
  "p": "tidyverse, camcorder, ggtext, osmdata, sf, sysfonts, showtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_20.R"
 },
 {
  "d": "2025-19-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 19,
  "t": "Projections",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_19.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_19.R",
  "l": "R",
  "p": "gridmappr, tidyverse, sf, showtext, patchwork, nrBrand",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_19.R"
 },
 {
  "d": "2025-18-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 18,
  "t": "Out of this World",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_18.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_18.R",
  "l": "R",
  "p": "rvest, tidyverse, sf, rnaturalearth, showtext, ggtext, ggfx, nrBrand, camcorder",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_18.R"
 },
 {
  "d": "2025-17-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 17,
  "t": "New tool",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_17.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_17.R",
  "l": "R",
  "p": "gridmappr, tidyverse, sf, rnaturalearth, showtext, ggtext, nrBrand, camcorder, readxl, rcartocolor, glue, devtools",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_17.R"
 },
 {
  "d": "2025-16-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 16,
  "t": "Cell",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_16.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_16.R",
  "l": "R",
  "p": "tidyverse, ggtext, nrBrand, showtext, ggforce, sf, elevatr, terra",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_16.R"
 },
 {
  "d": "2025-15-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 15,
  "t": "Fire",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_15.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_15.R",
  "l": "R",
  "p": "tidyverse, camcorder, sf, showtext, ggfx, gganimate",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_15.R"
 },
 {
  "d": "2025-14-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 14,
  "t": "OpenStreetMap",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_14.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_14.R",
  "l": "R",
  "p": "glue, tidyverse, camcorder, nrBrand, ggtext, osmdata, sf, sysfonts, showtext, tibble",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_14.R"
 },
 {
  "d": "2025-13-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 13,
  "t": "10 minute map",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_13.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_13.R",
  "l": "R",
  "p": "tidyverse, sf, osrm, ggmap, showtext, glue, ggtext, ggspatial, camcorder, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_13.R"
 },
 {
  "d": "2025-12-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 12,
  "t": "Map from 2125",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_12.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_12.R",
  "l": "R",
  "p": "tidyverse, sf, showtext, ggtext, ggfx, nrBrand",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_12.R"
 },
 {
  "d": "2025-11-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 11,
  "t": "Minimal",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_11.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_11.R",
  "l": "R",
  "p": "gapminder, geofacet, tidyverse, ggforce, camcorder, glue, nrBrand, ggtext, showtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_11.R"
 },
 {
  "d": "2025-10-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 10,
  "t": "Air",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_10.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_10.R",
  "l": "R",
  "p": "glue, tidyverse, camcorder, nrBrand, ggtext, openair, showtext, rnaturalearth, sf, ggnewscale",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_10.R"
 },
 {
  "d": "2025-09-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 9,
  "t": "Analog",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_09.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2025",
  "l": "Hand-drawn",
  "p": ""
 },
 {
  "d": "2025-08-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 8,
  "t": "Urban",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_08.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_08.R",
  "l": "R",
  "p": "glue, tidyverse, camcorder, nrBrand, patchwork, ggtext, sysfonts, showtext, tibble, sf, osmdata, dplyr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_08.R"
 },
 {
  "d": "2025-07-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 7,
  "t": "Accessibility",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_07.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_07.R",
  "l": "R",
  "p": "tidyverse, rnaturalearth, patchwork, showtext, ggtext, nrBrand, camcorder, glue, colorspace, cowplot, colorblindr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_07.R"
 },
 {
  "d": "2025-06-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 6,
  "t": "Dimensions",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_06.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_06.R",
  "l": "R",
  "p": "geodata, rayshader, ggplot2, tidyr, dplyr, viridis",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_06.R"
 },
 {
  "d": "2025-05-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 5,
  "t": "Earth",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_05.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_05.R",
  "l": "R",
  "p": "tidyverse, rnaturalearth, sf, patchwork, glue, showtext, nrBrand, ggtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_05.R"
 },
 {
  "d": "2025-05-karamanis-05-earth",
  "m": "karamanis",
  "y": "2025",
  "n": 5,
  "t": "Earth",
  "s": "nature index",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/05-earth/05-earth-nature-index.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/05-earth/05-earth-nature-index.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2025/05-earth/05-earth-nature-index.R",
  "l": "R",
  "p": "tidyverse, rvest, sf, camcorder, here, janitor, rnaturalearth, MetBrewer, ggrepel, scales"
 },
 {
  "d": "2025-04-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 4,
  "t": "My Data",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_04.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_04.R",
  "l": "R",
  "p": "tidyverse, gpx, sf, camcorder, ggtext, showtext, glue, osmdata",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_04.R"
 },
 {
  "d": "2025-04-karamanis-04-my-data",
  "m": "karamanis",
  "y": "2025",
  "n": 4,
  "t": "Data challenge: My Data",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/04-my-data/04-my-data.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/04-my-data/04-my-data.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2025/04-my-data/04-my-data.R",
  "l": "R",
  "p": "tidyverse, sf, patchwork, camcorder, here, rnaturalearth"
 },
 {
  "d": "2025-03-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 3,
  "t": "Polygons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_03.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_03.R",
  "l": "R",
  "p": "glue, sysfonts, showtext, osmdata, tibble, sf, dplyr, ggplot2, maprints, ggtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_03.R"
 },
 {
  "d": "2025-03-karamanis-03-polygons",
  "m": "karamanis",
  "y": "2025",
  "n": 3,
  "t": "Polygons",
  "s": "uu buildings",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/03-polygons/03-polygons-uu-buildings.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/03-polygons/03-polygons-uu-buildings.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2025/03-polygons/03-polygons-uu-buildings.R",
  "l": "R",
  "p": "tidyverse, patchwork, sf, osmdata, camcorder, here"
 },
 {
  "d": "2025-02-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 2,
  "t": "Lines",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_02.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_02.R",
  "l": "R",
  "p": "sysfonts, showtext, osmdata, tibble, sf, maprints, ggplot2",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_02.R"
 },
 {
  "d": "2025-02-karamanis-02-lines",
  "m": "karamanis",
  "y": "2025",
  "n": 2,
  "t": "Lines",
  "s": "alex",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/02-lines/02-lines-alex.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/02-lines/02-lines-alex.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2025/02-lines/02-lines-alex.R",
  "l": "R",
  "p": "tidyverse, jsonlite, sf, camcorder, here, rnaturalearth, ggrepel, scales"
 },
 {
  "d": "2025-01-nrennie",
  "m": "nrennie",
  "y": "2025",
  "n": 1,
  "t": "Points",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_01.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_01.R",
  "l": "R",
  "p": "tidyverse, showtext, camcorder, ggtext, nrBrand, glue, osmdata, sf, ggfx, tidytuesdayR",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_01.R"
 },
 {
  "d": "2025-01-karamanis-01-points",
  "m": "karamanis",
  "y": "2025",
  "n": 1,
  "t": "Points",
  "s": "orgs",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/01-points/01-points-orgs.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2025/01-points/01-points-orgs.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2025/01-points/01-points-orgs.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, rnaturalearth, MetBrewer, colorspace, ggrepel"
 },
 {
  "d": "2024-30-karamanis-30-final-basketglobe",
  "m": "karamanis",
  "y": "2024",
  "n": 30,
  "t": "The final map",
  "s": "basketglobe",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/30-final-basketglobe/30-final-basketglobe.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/30-final-basketglobe/30-final-basketglobe.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/30-final-basketglobe/30-final-basketglobe.R",
  "l": "R",
  "p": "tidyverse, sf, ggpath, grid, ggpp, camcorder, here, rnaturalearth, rmapshaper"
 },
 {
  "d": "2024-26-karamanis-26-map_projections-fiba_wc",
  "m": "karamanis",
  "y": "2024",
  "n": 26,
  "t": "Map projections",
  "s": "fiba wc",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/26-map_projections-fiba_wc/26-map_projections-fiba_wc.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/26-map_projections-fiba_wc/26-map_projections-fiba_wc.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/26-map_projections-fiba_wc/26-map_projections-fiba_wc.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, camcorder, here, janitor, ggrepel"
 },
 {
  "d": "2024-25-karamanis-25-heat-google_trends",
  "m": "karamanis",
  "y": "2024",
  "n": 25,
  "t": "Heat",
  "s": "google trends",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/25-heat-google_trends/25-heat-google_trends.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/25-heat-google_trends/25-heat-google_trends.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/25-heat-google_trends/25-heat-google_trends.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, MetBrewer"
 },
 {
  "d": "2024-24-karamanis-24-circles-euroleague",
  "m": "karamanis",
  "y": "2024",
  "n": 24,
  "t": "Only circular shapes",
  "s": "circles euroleague instagram",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/24-circles-euroleague/24-circles-euroleague-instagram.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/24-circles-euroleague/24-circles-euroleague-instagram.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/24-circles-euroleague/24-circles-euroleague-instagram.R",
  "l": "R",
  "p": "tidyverse, sf, rnaturalearth, scales, camcorder, here, ggforce"
 },
 {
  "d": "2024-22-karamanis-22-two-colors-nba-divisions",
  "m": "karamanis",
  "y": "2024",
  "n": 22,
  "t": "2 colours",
  "s": "two colors nba divisions",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/22-two-colors-nba-divisions/22-two-colors-nba-divisions.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/22-two-colors-nba-divisions/22-two-colors-nba-divisions.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/22-two-colors-nba-divisions/22-two-colors-nba-divisions.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, ggpattern, rnaturalearth, camcorder, here, janitor, ggrepel"
 },
 {
  "d": "2024-21-karamanis-21-conflict-nba_rivalries",
  "m": "karamanis",
  "y": "2024",
  "n": 21,
  "t": "Conflict",
  "s": "nba rivalries",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/21-conflict-nba_rivalries/21-conflict-nba_rivalries.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/21-conflict-nba_rivalries/21-conflict-nba_rivalries.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/21-conflict-nba_rivalries/21-conflict-nba_rivalries.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, rnaturalearth, here, ggrepel"
 },
 {
  "d": "2024-20-karamanis-20-osm-msg",
  "m": "karamanis",
  "y": "2024",
  "n": 20,
  "t": "OpenStreetMap",
  "s": "osm msg",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/20-osm-msg/20-osm-msg.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/20-osm-msg/20-osm-msg.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/20-osm-msg/20-osm-msg.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, ggrepel"
 },
 {
  "d": "2024-19-karamanis-19-typography-nba_state_wordcloud",
  "m": "karamanis",
  "y": "2024",
  "n": 19,
  "t": "Typography",
  "s": "nba state wordcloud california",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/19-typography-nba_state_wordcloud/19-typography-nba_state_wordcloud-california.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/19-typography-nba_state_wordcloud/19-typography-nba_state_wordcloud.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/19-typography-nba_state_wordcloud/19-typography-nba_state_wordcloud.R",
  "l": "R",
  "p": "tidyverse, tidytext, ggwordcloud, magick, camcorder, RedditExtractoR, here"
 },
 {
  "d": "2024-16-karamanis-16-choropleth-women_win_pct",
  "m": "karamanis",
  "y": "2024",
  "n": 16,
  "t": "Choropleth",
  "s": "women win pct",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/16-choropleth-women_win_pct/16-choropleth-women_win_pct.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/16-choropleth-women_win_pct/16-choropleth-women_win_pct.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/16-choropleth-women_win_pct/16-choropleth-women_win_pct.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, camcorder, here, janitor, countrycode, rnaturalearth, MetBrewer, ggrepel, scales"
 },
 {
  "d": "2024-12-karamanis-12-timespace-nba_relocated",
  "m": "karamanis",
  "y": "2024",
  "n": 12,
  "t": "Time and space",
  "s": "timespace nba relocated",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/12-timespace-nba_relocated/12-timespace-nba_relocated.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/12-timespace-nba_relocated/12-timespace-nba_relocated.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/12-timespace-nba_relocated/12-timespace-nba_relocated.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, camcorder, here, janitor, rnaturalearth, geomtextpath, ggrepel, MetBrewer"
 },
 {
  "d": "2024-11-karamanis-11-arctic-courts",
  "m": "karamanis",
  "y": "2024",
  "n": 11,
  "t": "Arctic",
  "s": "courts",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/11-arctic-courts/11-arctic-courts.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/11-arctic-courts/11-arctic-courts.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/11-arctic-courts/11-arctic-courts.R",
  "l": "R",
  "p": "tidyverse, sf, osmdata, grid, ggpp, camcorder, here, rnaturalearth, ggtext"
 },
 {
  "d": "2024-06-nrennie",
  "m": "nrennie",
  "y": "2024",
  "n": 6,
  "t": "Raster",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2024/maps/day_06.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2024/scripts/day_06.R",
  "l": "R",
  "p": "tidyverse, showtext, ggtext, nrBrand, geofacet, glue, tidytuesdayR",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2024/scripts/day_06.R"
 },
 {
  "d": "2024-06-karamanis-06-raster-distance_euroleague",
  "m": "karamanis",
  "y": "2024",
  "n": 6,
  "t": "Raster",
  "s": "distance euroleague",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/06-raster-distance_euroleague/06-raster-distance_euroleague.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/06-raster-distance_euroleague/06-raster-distance_euroleague.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/06-raster-distance_euroleague/06-raster-distance_euroleague.R",
  "l": "R",
  "p": "tidyverse, sf, terra, rnaturalearth, camcorder, here, ggrepel"
 },
 {
  "d": "2024-05-karamanis-05-journey-nba_champion",
  "m": "karamanis",
  "y": "2024",
  "n": 5,
  "t": "A journey",
  "s": "nba champion",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/05-journey-nba_champion/05-journey-nba_champion.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/05-journey-nba_champion/05-journey-nba_champion.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/05-journey-nba_champion/05-journey-nba_champion.R",
  "l": "R",
  "p": "tidyverse, sf, rgeoboundaries, geosphere, geomtextpath, camcorder, here, scales, rnaturalearth, rmapshaper, ggrepel, glue"
 },
 {
  "d": "2024-04-karamanis-04-hex-players_state",
  "m": "karamanis",
  "y": "2024",
  "n": 4,
  "t": "Hexagons",
  "s": "hex players state",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/04-hex-players_state/04-hex-players_state.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/04-hex-players_state/04-hex-players_state.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/04-hex-players_state/04-hex-players_state.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, camcorder, here, tidycensus, MetBrewer, ggtext"
 },
 {
  "d": "2024-03-karamanis-03-polygons-birthplaces",
  "m": "karamanis",
  "y": "2024",
  "n": 3,
  "t": "Polygons",
  "s": "birthplaces",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/03-polygons-birthplaces/03-polygons-birthplaces.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/03-polygons-birthplaces/03-polygons-birthplaces.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/03-polygons-birthplaces/03-polygons-birthplaces.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, camcorder, here, rnaturalearth, janitor, MetBrewer, ggrepel, ggtext"
 },
 {
  "d": "2024-02-karamanis-02-lines-euroleague_movements",
  "m": "karamanis",
  "y": "2024",
  "n": 2,
  "t": "Lines",
  "s": "euroleague movements",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/02-lines-euroleague_movements/02-lines-euroleague-movements-1.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/02-lines-euroleague_movements/02-lines-euroleague-movements.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/02-lines-euroleague_movements/02-lines-euroleague-movements.R",
  "l": "R",
  "p": "tidyverse, sf, rvest, geosphere, marquee, camcorder, here, janitor, ggrepel"
 },
 {
  "d": "2024-01-karamanis-01-points-ny_courts",
  "m": "karamanis",
  "y": "2024",
  "n": 1,
  "t": "Points",
  "s": "ny courts",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/01-points-ny_courts/01-points-ny_courts.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2024/01-points-ny_courts/01-points-ny_courts.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2024/01-points-ny_courts/01-points-ny_courts.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, jsonlite, rnaturalearth, ggtext"
 },
 {
  "d": "2023-26-nrennie",
  "m": "nrennie",
  "y": "2023",
  "n": 26,
  "t": "Minimal",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/maps/day_26.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2023/scripts/day_26.R",
  "l": "R",
  "p": "tibble, dplyr, sf, rgeoboundaries, sysfonts, showtext, nrBrand, ggplot2, ggtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/scripts/day_26.R"
 },
 {
  "d": "2023-05-nrennie",
  "m": "nrennie",
  "y": "2023",
  "n": 5,
  "t": "Analog",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/maps/day_05.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2023/scripts/day_05.R",
  "l": "R",
  "p": "tidyverse, ggtext, sf, nrBrand, showtext, rgeoboundaries, elevatr, terra",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/scripts/day_05.R"
 },
 {
  "d": "2023-02-nrennie",
  "m": "nrennie",
  "y": "2023",
  "n": 2,
  "t": "Lines",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/maps/day_02.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2023/scripts/day_02.py",
  "l": "Python",
  "p": "ridge_map, matplotlib, numpy",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/scripts/day_02.py"
 },
 {
  "d": "2023-01-karamanis-01-points-lgbt-events",
  "m": "karamanis",
  "y": "2023",
  "n": 1,
  "t": "Points",
  "s": "lgbt events",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2023/01-points-lgbt-events/01-points-lgbt-events.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2023/01-points-lgbt-events/01-points-lgbt-events.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2023/01-points-lgbt-events/01-points-lgbt-events.R",
  "l": "R",
  "p": "tidyverse, rvest, camcorder, here, janitor, rnaturalearthdata, sf, ggrepel, scales, MetBrewer"
 },
 {
  "d": "2022-30-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 30,
  "t": "Remix",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_30.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_30.R",
  "l": "R",
  "p": "leaflet, tidyverse, sf, mapview, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_30.R"
 },
 {
  "d": "2022-29-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 29,
  "t": "Out of Comfort Zone",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_29.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_29.py",
  "l": "Python",
  "p": "geopandas, matplotlib, mpl_toolkits",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_29.py"
 },
 {
  "d": "2022-28-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 28,
  "t": "3D",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_28.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_28.R",
  "l": "R",
  "p": "rayshader, elevatr, tidyverse, sf, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_28.R"
 },
 {
  "d": "2022-27-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 27,
  "t": "Music",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_27.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_27.R",
  "l": "R",
  "p": "tidyverse, showtext, camcorder, ggforce, geofacet, ggtext, rcartocolor, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_27.R"
 },
 {
  "d": "2022-26-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 26,
  "t": "Islands",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_26.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_26.R",
  "l": "R",
  "p": "tidyverse, sf, showtext, ggrepel, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_26.R"
 },
 {
  "d": "2022-25-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 25,
  "t": "Two Colours",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_25.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_25.R",
  "l": "R",
  "p": "tidyverse, sf, biscale, cowplot, showtext, ons, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_25.R"
 },
 {
  "d": "2022-24-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 24,
  "t": "Fantasy)",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_24.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_24.R",
  "l": "R",
  "p": "tidyverse, sf, showtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_24.R"
 },
 {
  "d": "2022-24-karamanis-24-fantasy-1279",
  "m": "karamanis",
  "y": "2022",
  "n": 24,
  "t": "Fantasy",
  "s": "1279",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/24-fantasy-1279/24-fantasy-1279.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/24-fantasy-1279/24-fantasy-1279.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/24-fantasy-1279/24-fantasy-1279.R",
  "l": "R",
  "p": "tidyverse, sf, ggsn, camcorder, here, janitor"
 },
 {
  "d": "2022-23-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 23,
  "t": "Movement",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_23.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_23.R",
  "l": "R",
  "p": "tidyverse, ggmap, osmdata, rcartocolor, rStrava, gganimate",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_23.R"
 },
 {
  "d": "2022-23-karamanis-23-movement-currents",
  "m": "karamanis",
  "y": "2022",
  "n": 23,
  "t": "Movement",
  "s": "currents",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/23-movement-currents/23-movement-currents.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/23-movement-currents/23-movement-currents.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/23-movement-currents/23-movement-currents.R",
  "l": "R",
  "p": "tidyverse, sf, ggtext, camcorder, here, giscoR, ggrepel"
 },
 {
  "d": "2022-22-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 22,
  "t": "NULL",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_22.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_22.R",
  "l": "R",
  "p": "tidyverse, sf, showtext, ons, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_22.R"
 },
 {
  "d": "2022-21-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 21,
  "t": "Kontur Population Data",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_21.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_21.R",
  "l": "R",
  "p": "scico, R.utils, tidyverse, sf, showtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_21.R"
 },
 {
  "d": "2022-21-karamanis-21-kontur-1000",
  "m": "karamanis",
  "y": "2022",
  "n": 21,
  "t": "Data: Kontur Population Dataset",
  "s": "1000",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/21-kontur-1000/21-kontur-1000.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/21-kontur-1000/21-kontur-1000.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/21-kontur-1000/21-kontur-1000.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here"
 },
 {
  "d": "2022-20-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 20,
  "t": "My Favourite ...",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_20.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_20.R",
  "l": "R",
  "p": "tidyverse, sf, rcartocolor, showtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_20.R"
 },
 {
  "d": "2022-20-karamanis-20-my-favourite-dataviz",
  "m": "karamanis",
  "y": "2022",
  "n": 20,
  "t": "\"My favourite…\"",
  "s": "dataviz",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/20-my-favourite-dataviz/20-my-favourite-dataviz.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/20-my-favourite-dataviz/20-my-favourite-dataviz.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/20-my-favourite-dataviz/20-my-favourite-dataviz.R",
  "l": "R",
  "p": "tidyverse, sf, imago, countrycode, camcorder, here, scico"
 },
 {
  "d": "2022-19-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 19,
  "t": "Globe",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_19.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_19.R",
  "l": "R",
  "p": "tidyverse",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_19.R"
 },
 {
  "d": "2022-19-karamanis-19-globe-volcanoes",
  "m": "karamanis",
  "y": "2022",
  "n": 19,
  "t": "Globe",
  "s": "volcanoes",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/19-globe-volcanoes/19-globe-volcanoes.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/19-globe-volcanoes/19-globe-volcanoes.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/19-globe-volcanoes/19-globe-volcanoes.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here"
 },
 {
  "d": "2022-18-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 18,
  "t": "Blue",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_18.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_18.R",
  "l": "R",
  "p": "tanaka, elevatr, terra, PrettyCols",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_18.R"
 },
 {
  "d": "2022-18-karamanis-18-blue-depression",
  "m": "karamanis",
  "y": "2022",
  "n": 18,
  "t": "Colour Friday: Blue",
  "s": "depression",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/18-blue-depression/18-blue-depression.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/18-blue-depression/18-blue-depression.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/18-blue-depression/18-blue-depression.R",
  "l": "R",
  "p": "tidyverse, cartogram, sf, camcorder, here, janitor, scico"
 },
 {
  "d": "2022-17-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 17,
  "t": "Without a Computer",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_17.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2022",
  "l": "Hand-drawn",
  "p": ""
 },
 {
  "d": "2022-16-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 16,
  "t": "Minimal",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_16.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_16.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_16.R"
 },
 {
  "d": "2022-16-karamanis-16-minimal-world",
  "m": "karamanis",
  "y": "2022",
  "n": 16,
  "t": "Minimal",
  "s": "world",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/16-minimal-world/16-minimal-world.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/16-minimal-world/16-minimal-world.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/16-minimal-world/16-minimal-world.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, giscoR, rmapshaper, smoothr"
 },
 {
  "d": "2022-15-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 15,
  "t": "Food / Drink",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_15.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_15.R",
  "l": "R",
  "p": "tidyverse, sf, cowplot, grid, nngeo, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_15.R"
 },
 {
  "d": "2022-15-karamanis-15-food-drink-meat",
  "m": "karamanis",
  "y": "2022",
  "n": 15,
  "t": "Food/drink",
  "s": "meat",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/15-food-drink-meat/15-food-drink-meat.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/15-food-drink-meat/15-food-drink-meat.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/15-food-drink-meat/15-food-drink-meat.R",
  "l": "R",
  "p": "tidyverse, sf, biscale, patchwork, ggtext, camcorder, here, janitor, grid"
 },
 {
  "d": "2022-14-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 14,
  "t": "Hexagons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_14.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_14.R",
  "l": "R",
  "p": "tidyverse, geojsonio, usefunc, rcartocolor, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_14.R"
 },
 {
  "d": "2022-14-karamanis-14-hex-solar",
  "m": "karamanis",
  "y": "2022",
  "n": 14,
  "t": "Hexagons",
  "s": "hex solar",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/14-hex-solar/14-hex-solar.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/14-hex-solar/14-hex-solar.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/14-hex-solar/14-hex-solar.R",
  "l": "R",
  "p": "tidyverse, sf, scico, camcorder, here, terra"
 },
 {
  "d": "2022-13-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 13,
  "t": "5 Minutes",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_13.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_13.R",
  "l": "R",
  "p": "osrm, sf, tidyverse, ggmap, ggtext",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_13.R"
 },
 {
  "d": "2022-13-karamanis-13-5min-first-letter",
  "m": "karamanis",
  "y": "2022",
  "n": 13,
  "t": "5 minute map",
  "s": "5min first letter",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/13-5min-first-letter/13-5min-first-letter.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/13-5min-first-letter/13-5min-first-letter.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/13-5min-first-letter/13-5min-first-letter.R",
  "l": "R",
  "p": "tidyverse, camcorder, here"
 },
 {
  "d": "2022-12-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 12,
  "t": "Scale",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_12.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_12.R",
  "l": "R",
  "p": "tidyverse, sf, PrettyCols, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_12.R"
 },
 {
  "d": "2022-12-karamanis-12-scale-tomato",
  "m": "karamanis",
  "y": "2022",
  "n": 12,
  "t": "Scale",
  "s": "tomato",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/12-scale-tomato/12-scale-tomato.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/12-scale-tomato/12-scale-tomato.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/12-scale-tomato/12-scale-tomato.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, patchwork, here, janitor, rmapshaper, lwgeom, RColorBrewer, scales"
 },
 {
  "d": "2022-11-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 11,
  "t": "Red",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_11.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_11.R",
  "l": "R",
  "p": "tidyverse, sf, osmdata, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_11.R"
 },
 {
  "d": "2022-11-karamanis-11-red-tomato",
  "m": "karamanis",
  "y": "2022",
  "n": 11,
  "t": "Colour Friday: Red",
  "s": "tomato",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/11-red-tomato/11-red-tomato.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/11-red-tomato/11-red-tomato.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/11-red-tomato/11-red-tomato.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, janitor, rmapshaper, lwgeom, RColorBrewer, scales"
 },
 {
  "d": "2022-10-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 10,
  "t": "A Bad Map",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_10.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_10.R",
  "l": "R",
  "p": "tidyverse, sf, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_10.R"
 },
 {
  "d": "2022-10-karamanis-10-bad-bp",
  "m": "karamanis",
  "y": "2022",
  "n": 10,
  "t": "A bad map",
  "s": "bp",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/10-bad-bp/10-bad-bp.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/10-bad-bp/10-bad-bp.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/10-bad-bp/10-bad-bp.R",
  "l": "R",
  "p": "tidyverse, ggsn, camcorder, here, janitor"
 },
 {
  "d": "2022-09-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 9,
  "t": "Space",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_09.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_09.R",
  "l": "R",
  "p": "tidyverse, ggforce, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_09.R"
 },
 {
  "d": "2022-09-karamanis-09-space-satellites",
  "m": "karamanis",
  "y": "2022",
  "n": 9,
  "t": "Space",
  "s": "satellites",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/09-space-satellites/09-space-satellites.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/09-space-satellites/09-space-satellites.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/09-space-satellites/09-space-satellites.R",
  "l": "R",
  "p": "rvest, tidyverse, ggshadow, camcorder, here, janitor"
 },
 {
  "d": "2022-08-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 8,
  "t": "OpenStreetMap Data",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_08.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_08.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_08.R"
 },
 {
  "d": "2022-08-karamanis-08-openstreetmap-shops",
  "m": "karamanis",
  "y": "2022",
  "n": 8,
  "t": "Data: OpenStreetMap",
  "s": "shops",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/08-openstreetmap-shops/08-openstreetmap-shops.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/08-openstreetmap-shops/08-openstreetmap-shops.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/08-openstreetmap-shops/08-openstreetmap-shops.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here"
 },
 {
  "d": "2022-07-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 7,
  "t": "Raster",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_07.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_07.R",
  "l": "R",
  "p": "tidyverse, sf, stars, PrettyCols, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_07.R"
 },
 {
  "d": "2022-07-karamanis-07-raster-earth",
  "m": "karamanis",
  "y": "2022",
  "n": 7,
  "t": "Raster",
  "s": "earth",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/07-raster-earth/07-raster-earth.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/07-raster-earth/07-raster-earth.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/07-raster-earth/07-raster-earth.R",
  "l": "R",
  "p": "tidyverse, marmap, tidyterra, ggnewscale, camcorder, here, raster, sf"
 },
 {
  "d": "2022-06-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 6,
  "t": "Network",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_06.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_06.R",
  "l": "R",
  "p": "tidyverse, sf, osmdata",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_06.R"
 },
 {
  "d": "2022-06-karamanis-06-network-power",
  "m": "karamanis",
  "y": "2022",
  "n": 6,
  "t": "Network",
  "s": "power",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/06-network-power/06-network-power.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/06-network-power/06-network-power.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/06-network-power/06-network-power.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here"
 },
 {
  "d": "2022-05-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 5,
  "t": "Ukraine",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_05.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_05.R",
  "l": "R",
  "p": "tidyverse, sf, rnaturalearth",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_05.R"
 },
 {
  "d": "2022-05-karamanis-05-ukraine-aid",
  "m": "karamanis",
  "y": "2022",
  "n": 5,
  "t": "Ukraine",
  "s": "aid",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/05-ukraine-aid/05-ukraine-aid.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/05-ukraine-aid/05-ukraine-aid.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/05-ukraine-aid/05-ukraine-aid.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, xlsx, readxl, janitor, rmapshaper"
 },
 {
  "d": "2022-04-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 4,
  "t": "Green",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_04.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_04.R",
  "l": "R",
  "p": "tidyverse, PrettyCols, readr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_04.R"
 },
 {
  "d": "2022-04-karamanis-04-green-flags",
  "m": "karamanis",
  "y": "2022",
  "n": 4,
  "t": "Colour Friday: Green",
  "s": "flags",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/04-green-flags/04-green-flags.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/04-green-flags/04-green-flags.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/04-green-flags/04-green-flags.R",
  "l": "R",
  "p": "tidyverse, sf, ggtext, camcorder, here, rmapshaper"
 },
 {
  "d": "2022-03-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 3,
  "t": "Polygons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_03.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_03.R",
  "l": "R",
  "p": "tidyverse, sf, tmap, viridis, rnaturalearth",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_03.R"
 },
 {
  "d": "2022-03-karamanis-03-polygons-forestbiomes",
  "m": "karamanis",
  "y": "2022",
  "n": 3,
  "t": "Polygons",
  "s": "forestbiomes",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/03-polygons-forestbiomes/03-polygons-forestbiomes.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/03-polygons-forestbiomes/03-polygons-forestbiomes.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/03-polygons-forestbiomes/03-polygons-forestbiomes.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here, MetBrewer"
 },
 {
  "d": "2022-02-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 2,
  "t": "Lines",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_02.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_02.R",
  "l": "R",
  "p": "tidyverse, sf, roughsf, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_02.R"
 },
 {
  "d": "2022-02-karamanis-02-lines-railways",
  "m": "karamanis",
  "y": "2022",
  "n": 2,
  "t": "Lines",
  "s": "railways",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/02-lines-railways/02-lines-railways.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/02-lines-railways/02-lines-railways.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/02-lines-railways/02-lines-railways.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here"
 },
 {
  "d": "2022-01-nrennie",
  "m": "nrennie",
  "y": "2022",
  "n": 1,
  "t": "Points",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_01.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_01.R",
  "l": "R",
  "p": "tidyverse, sf, cowplot, grid, readr, ons",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_01.R"
 },
 {
  "d": "2022-01-karamanis-01-points-cities5000",
  "m": "karamanis",
  "y": "2022",
  "n": 1,
  "t": "Points",
  "s": "cities5000",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/01-points-cities5000/01-points-cities5000.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2022/01-points-cities5000/01-points-cities5000.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2022/01-points-cities5000/01-points-cities5000.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, here"
 },
 {
  "d": "2021-30-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 30,
  "t": "Metamapping",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_30.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_30.R",
  "l": "R",
  "p": "tidyverse, rcartocolor",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_30.R"
 },
 {
  "d": "2021-29-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 29,
  "t": "Null",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_29.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_29.R",
  "l": "R",
  "p": "osrm, sf, tidyverse, ggmap, ragg",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_29.R"
 },
 {
  "d": "2021-28-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 28,
  "t": "The Earth is not flat",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_28.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_28.R",
  "l": "R",
  "p": "rayshader, reshape2, raster, tidyverse, rgdal",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_28.R"
 },
 {
  "d": "2021-28-karamanis-28-not-flat",
  "m": "karamanis",
  "y": "2021",
  "n": 28,
  "t": "The Earth is not flat",
  "s": "circle",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/28-not-flat/28-not-flat-circle.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/28-not-flat/28-not-flat-circle.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/28-not-flat/28-not-flat-circle.R",
  "l": "R",
  "p": "tidyverse, camcorder"
 },
 {
  "d": "2021-27-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 27,
  "t": "Heatmap",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_27.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_27.R",
  "l": "R",
  "p": "ggplot2, sf, rcartocolor, dplyr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_27.R"
 },
 {
  "d": "2021-27-karamanis-27-heatmap",
  "m": "karamanis",
  "y": "2021",
  "n": 27,
  "t": "Heatmap",
  "s": "restaurants",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/27-heatmap/27-heatmap-restaurants.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/27-heatmap/27-heatmap-restaurants.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/27-heatmap/27-heatmap-restaurants.R",
  "l": "R",
  "p": "tidyverse, camcorder, rgeoboundaries, sfheaders"
 },
 {
  "d": "2021-26-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 26,
  "t": "Choropleth map",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_26.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_26.R",
  "l": "R",
  "p": "tidyverse, cowplot, showtext, ragg, biscale, sf",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_26.R"
 },
 {
  "d": "2021-25-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 25,
  "t": "Interactive map",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_25.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_25.R",
  "l": "R",
  "p": "leaflet, htmlwidgets, sf, dplyr, MapColoring, CEoptim, rcartocolor",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_25.R"
 },
 {
  "d": "2021-25-karamanis-25-26-interactive-choropleth",
  "m": "karamanis",
  "y": "2021",
  "n": 25,
  "t": "Interactive map",
  "s": "choropleth gas",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/25-26-interactive-choropleth/25-26-interactive-choropleth-gas.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/25-26-interactive-choropleth/25-26-interactive-choropleth-gas.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/25-26-interactive-choropleth/25-26-interactive-choropleth-gas.R",
  "l": "R",
  "p": "tidyverse, sf, tabulizer, fuzzyjoin, mapdeck, janitor"
 },
 {
  "d": "2021-24-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 24,
  "t": "Historical map",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_24.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_24.R",
  "l": "R",
  "p": "sf, sp, ggplot2, rcartocolor, MapColoring, CEoptim, devtools",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_24.R"
 },
 {
  "d": "2021-23-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 23,
  "t": "GHSL",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_23.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_23.R",
  "l": "R",
  "p": "raster, sp, leaflet, rcartocolor",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_23.R"
 },
 {
  "d": "2021-22-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 22,
  "t": "Boundaries",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_22.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_22.R",
  "l": "R",
  "p": "sf, ggplot2, roughsf, dplyr",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_22.R"
 },
 {
  "d": "2021-22-karamanis-22-boundaries",
  "m": "karamanis",
  "y": "2021",
  "n": 22,
  "t": "Boundaries",
  "s": "tectonic",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/22-boundaries/22-boundaries-tectonic.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/22-boundaries/22-boundaries-tectonic.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/22-boundaries/22-boundaries-tectonic.R",
  "l": "R",
  "p": "sf, tidyverse, camcorder, janitor"
 },
 {
  "d": "2021-21-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 21,
  "t": "Elevation",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_21.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_21.R",
  "l": "R",
  "p": "tidyverse, rayshader, raster, rgdal, png",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_21.R"
 },
 {
  "d": "2021-21-karamanis-21-elevation",
  "m": "karamanis",
  "y": "2021",
  "n": 21,
  "t": "Elevation",
  "s": "crete blender",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/21-elevation/21-elevation-crete-blender.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/21-elevation/21-elevation.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/21-elevation/21-elevation.R",
  "l": "R",
  "p": "elevatr, rgeoboundaries, tidyverse, raster, camcorder, rayshader"
 },
 {
  "d": "2021-20-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 20,
  "t": "Movement",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_20.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_20.R",
  "l": "R",
  "p": "sf, ggplot2, dplyr, rcartocolor",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_20.R"
 },
 {
  "d": "2021-20-karamanis-20-movement",
  "m": "karamanis",
  "y": "2021",
  "n": 20,
  "t": "Movement",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/20-movement/20-movement.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/20-movement/20-movement.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/20-movement/20-movement.R",
  "l": "R",
  "p": "raster, dplyr, ggplot2, camcorder, rgeoboundaries, scales"
 },
 {
  "d": "2021-19-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 19,
  "t": "Island(s)",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_19.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_19.R",
  "l": "R",
  "p": "sf, ggplot2, dplyr, magick, cowplot",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_19.R"
 },
 {
  "d": "2021-19-karamanis-19-islands",
  "m": "karamanis",
  "y": "2021",
  "n": 19,
  "t": "Island(s)",
  "s": "islands greece",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/19-islands/19-islands-greece.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/19-islands/19-islands-greece.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/19-islands/19-islands-greece.R",
  "l": "R",
  "p": "sf, tidyverse, camcorder, shadowtext, rgeoboundaries, here, colorspace"
 },
 {
  "d": "2021-18-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 18,
  "t": "Water",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_18.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_18.R",
  "l": "R",
  "p": "marmap, ggplot2",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_18.R"
 },
 {
  "d": "2021-18-karamanis-18-water",
  "m": "karamanis",
  "y": "2021",
  "n": 18,
  "t": "Water",
  "s": "coastal",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/18-water/18-water-coastal.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/18-water/18-water-coastal.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/18-water/18-water-coastal.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, ggtext, colorspace, grid"
 },
 {
  "d": "2021-17-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 17,
  "t": "Land",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_17.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_17.R",
  "l": "R",
  "p": "sf, ggplot2, dplyr, pals",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_17.R"
 },
 {
  "d": "2021-16-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 16,
  "t": "Urban/rural",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_16.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_16.R",
  "l": "R",
  "p": "sf, ggplot2, rcartocolor, cowplot, magick",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_16.R"
 },
 {
  "d": "2021-16-karamanis-16-urban-rural",
  "m": "karamanis",
  "y": "2021",
  "n": 16,
  "t": "Urban/rural",
  "s": "dgurba",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/16-urban-rural/16-urban-rural-dgurba.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/16-urban-rural/16-urban-rural-dgurba.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/16-urban-rural/16-urban-rural-dgurba.R",
  "l": "R",
  "p": "sf, tidyverse, camcorder, colorspace"
 },
 {
  "d": "2021-15-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 15,
  "t": "Map without a computer",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_15.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2021",
  "l": "Hand-drawn",
  "p": ""
 },
 {
  "d": "2021-14-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 14,
  "t": "Map with a new tool",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_14.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2021",
  "l": "Tableau",
  "p": ""
 },
 {
  "d": "2021-14-karamanis-14-new-tool",
  "m": "karamanis",
  "y": "2021",
  "n": 14,
  "t": "Map with a new tool",
  "s": "geotype",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/14-new-tool/14-new-tool-geotype.png",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/tree/main/2021/14-new-tool",
  "l": "Other",
  "p": ""
 },
 {
  "d": "2021-13-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 13,
  "t": "Natural Earth",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_13.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_13.R",
  "l": "R",
  "p": "rnaturalearth, rnaturalearthdata, ggplot2, sf, ggspatial, rcartocolor",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_13.R"
 },
 {
  "d": "2021-13-karamanis-13-naturalearth",
  "m": "karamanis",
  "y": "2021",
  "n": 13,
  "t": "Data challenge 2: Natural Earth",
  "s": "naturalearth greece",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/13-naturalearth/13-naturalearth-greece.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/13-naturalearth/13-naturalearth-greece.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/13-naturalearth/13-naturalearth-greece.R",
  "l": "R",
  "p": "rnaturalearth, dplyr, ggplot2, sf, rgeoboundaries, rcartocolor, camcorder, raster, colorspace"
 },
 {
  "d": "2021-12-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 12,
  "t": "Population",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_12.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_12.R",
  "l": "R",
  "p": "sf, dplyr, readr, ggplot2, RColorBrewer, geofacet, cowplot, patchwork",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_12.R"
 },
 {
  "d": "2021-12-karamanis-12-population",
  "m": "karamanis",
  "y": "2021",
  "n": 12,
  "t": "Population",
  "s": "greece",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/12-population/12-population-greece.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/12-population/12-population-greece.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/12-population/12-population-greece.R",
  "l": "R",
  "p": "tidyverse, sf, camcorder, scico, cartogram, janitor, readxl"
 },
 {
  "d": "2021-11-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 11,
  "t": "3D",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_11.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_11.R",
  "l": "R",
  "p": "sf, dplyr, stringr, readr, ggplot2, cowplot, extrafont, magick, rayshader",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_11.R"
 },
 {
  "d": "2021-10-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 10,
  "t": "Raster",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_10.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_10.R",
  "l": "R",
  "p": "elevatr, rayshader, sf, rgeoboundaries, tidyverse",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_10.R"
 },
 {
  "d": "2021-10-karamanis-10-raster",
  "m": "karamanis",
  "y": "2021",
  "n": 10,
  "t": "Raster",
  "s": "afrimapr",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/10-raster/10-raster-afrimapr.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/10-raster/10-raster-afrimapr.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/10-raster/10-raster-afrimapr.R",
  "l": "R",
  "p": "tidyverse, camcorder, afrilearndata, scico"
 },
 {
  "d": "2021-09-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 9,
  "t": "Monochrome",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_09.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_09.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf, cowplot",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_09.R"
 },
 {
  "d": "2021-09-karamanis-09-monochrome",
  "m": "karamanis",
  "y": "2021",
  "n": 9,
  "t": "Monochrome",
  "s": "elevation",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/09-monochrome/09-monochrome-elevation.png",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/tree/main/2021/09-monochrome",
  "l": "Other",
  "p": ""
 },
 {
  "d": "2021-08-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 8,
  "t": "Blue",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_08.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_08.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf, cowplot, ggmap, patchwork",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_08.R"
 },
 {
  "d": "2021-08-karamanis-08-blue",
  "m": "karamanis",
  "y": "2021",
  "n": 8,
  "t": "Blue",
  "s": "bathy",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/08-blue/08-blue-bathy.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/08-blue/08-blue-bathy.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/08-blue/08-blue-bathy.R",
  "l": "R",
  "p": "marmap, tidyverse, camcorder, sf, rgeoboundaries"
 },
 {
  "d": "2021-07-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 7,
  "t": "Green",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_07.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_07.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf, cowplot, ggmap, patchwork",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_07.R"
 },
 {
  "d": "2021-07-karamanis-07-green",
  "m": "karamanis",
  "y": "2021",
  "n": 7,
  "t": "Green",
  "s": "vegetation",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/07-green/07-green-vegetation.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/07-green/07-green-vegetation.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/07-green/07-green-vegetation.R",
  "l": "R",
  "p": "tidyverse, camcorder, sf, raster, MODIStsp, rayshader, here"
 },
 {
  "d": "2021-06-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 6,
  "t": "Red",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_06.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_06.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf, cowplot",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_06.R"
 },
 {
  "d": "2021-06-karamanis-06-red",
  "m": "karamanis",
  "y": "2021",
  "n": 6,
  "t": "Red",
  "s": "temp",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/06-red/06-red-temp.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/06-red/06-red-temp.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/06-red/06-red-temp.R",
  "l": "R",
  "p": "tidyverse, raster, camcorder, rgeoboundaries, sf"
 },
 {
  "d": "2021-05-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 5,
  "t": "OpenStreetMap",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_05.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_05.R",
  "l": "R",
  "p": "tidyverse, osmdata, sf, ggmap, cowplot",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_05.R"
 },
 {
  "d": "2021-05-karamanis-05-osm",
  "m": "karamanis",
  "y": "2021",
  "n": 5,
  "t": "Data challenge 1: OpenStreetMap",
  "s": "osm speed",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/05-osm/05-osm-speed.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/05-osm/05-osm-speed.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/05-osm/05-osm-speed.R",
  "l": "R",
  "p": "osmdata, tidyverse, camcorder, sf, wesanderson"
 },
 {
  "d": "2021-04-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 4,
  "t": "Hexagons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_04.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_04.R",
  "l": "R",
  "p": "tidyverse, viridis, ggplot2, stringr, sf, dplyr, readr, cowplot, extrafont, magick, hexbin",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_04.R"
 },
 {
  "d": "2021-04-karamanis-04-hexagons",
  "m": "karamanis",
  "y": "2021",
  "n": 4,
  "t": "Hexagons",
  "s": "saint",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/04-hexagons/04-hexagons-saint.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/04-hexagons/04-hexagons-saint.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/04-hexagons/04-hexagons-saint.R",
  "l": "R",
  "p": "tidyverse, camcorder, wesanderson, sf, ggtext, janitor"
 },
 {
  "d": "2021-03-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 3,
  "t": "Polygons",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_03.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_03.R",
  "l": "R",
  "p": "sf, dplyr, stringr, readr, ggplot2, cowplot, extrafont, magick",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_03.R"
 },
 {
  "d": "2021-03-karamanis-03-polygons",
  "m": "karamanis",
  "y": "2021",
  "n": 3,
  "t": "Polygons",
  "s": "wildlife",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/03-polygons/03-polygons-wildlife.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/03-polygons/03-polygons-wildlife.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/03-polygons/03-polygons-wildlife.R",
  "l": "R",
  "p": "ggplot2, camcorder, sf, ggpattern, ggtext, rmapshaper"
 },
 {
  "d": "2021-02-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 2,
  "t": "Lines",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_02.png",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_02.R",
  "l": "R",
  "p": "sf, raster, dplyr, spData, spDataLarge, tmap, leaflet, ggplot2, maptools, sp",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_02.R"
 },
 {
  "d": "2021-02-karamanis-02-lines",
  "m": "karamanis",
  "y": "2021",
  "n": 2,
  "t": "Lines",
  "s": "ferries",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/02-lines/02-lines-ferries.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/02-lines/02-lines-ferries.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/02-lines/02-lines-ferries.R",
  "l": "R",
  "p": "tidyverse, camcorder, sf, rmapshaper, here"
 },
 {
  "d": "2021-01-nrennie",
  "m": "nrennie",
  "y": "2021",
  "n": 1,
  "t": "Points",
  "s": "",
  "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_01.jpg",
  "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_01.R",
  "l": "R",
  "p": "sf, dplyr, stringr, readr, ggplot2, cowplot, extrafont, magick",
  "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_01.R"
 },
 {
  "d": "2021-01-karamanis-01-points",
  "m": "karamanis",
  "y": "2021",
  "n": 1,
  "t": "Points",
  "s": "heating",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/01-points/01-points-heating.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2021/01-points/01-points-heating.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2021/01-points/01-points-heating.R",
  "l": "R",
  "p": "tidyverse, sf, here"
 },
 {
  "d": "2020-28-karamanis-28-non-geographic",
  "m": "karamanis",
  "y": "2020",
  "n": 28,
  "t": "Non-geographic map",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/28-non-geographic/28-non-geographic.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/28-non-geographic/28-non-geographic.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/28-non-geographic/28-non-geographic.R",
  "l": "R",
  "p": "tidyverse, ggforce, here"
 },
 {
  "d": "2020-22-karamanis-22-movement",
  "m": "karamanis",
  "y": "2020",
  "n": 22,
  "t": "Movement",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/22-movement/22-movement.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/22-movement/22-movement.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/22-movement/22-movement.R",
  "l": "R",
  "p": "tidyverse, readxl, janitor, tidygeocoder, geosphere, maps, here"
 },
 {
  "d": "2020-21-karamanis-21-water",
  "m": "karamanis",
  "y": "2020",
  "n": 21,
  "t": "Water",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/21-water/21-water.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/21-water/21-water.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/21-water/21-water.R",
  "l": "R",
  "p": "sf, tidyverse, janitor, maps, here"
 },
 {
  "d": "2020-16-karamanis-16-islands",
  "m": "karamanis",
  "y": "2020",
  "n": 16,
  "t": "Island(s)",
  "s": "islands",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/16-islands/16-islands.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/16-islands/16-islands.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/16-islands/16-islands.R",
  "l": "R",
  "p": "sf, tidyverse, janitor, maps, sfheaders, here"
 },
 {
  "d": "2020-15-karamanis-15-network",
  "m": "karamanis",
  "y": "2020",
  "n": 15,
  "t": "Connections",
  "s": "network",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/15-network/15-network.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/15-network/15-network.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/15-network/15-network.R",
  "l": "R",
  "p": "sf, tidyverse, janitor, maps, sfheaders, here"
 },
 {
  "d": "2020-09-karamanis-9-monochrome",
  "m": "karamanis",
  "y": "2020",
  "n": 9,
  "t": "Monochrome",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/9-monochrome/9-monochrome.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/9-monochrome/9-monochrome.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/9-monochrome/9-monochrome.R",
  "l": "R",
  "p": "tidyverse, sf, janitor, here"
 },
 {
  "d": "2020-08-karamanis-8-yellow",
  "m": "karamanis",
  "y": "2020",
  "n": 8,
  "t": "Yellow",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/8-yellow/8-yellow.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/8-yellow/8-yellow.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/8-yellow/8-yellow.R",
  "l": "R",
  "p": "tidyverse, sf, janitor, here"
 },
 {
  "d": "2020-05-karamanis-5-blue",
  "m": "karamanis",
  "y": "2020",
  "n": 5,
  "t": "Blue",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/5-blue/5-blue.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/5-blue/5-blue.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/5-blue/5-blue.R",
  "l": "R",
  "p": "tidyverse, sf, janitor, here"
 },
 {
  "d": "2020-03-karamanis-3-polygons",
  "m": "karamanis",
  "y": "2020",
  "n": 3,
  "t": "Polygons",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/3-polygons/3-polygons.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/3-polygons/3-polygons.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/3-polygons/3-polygons.R",
  "l": "R",
  "p": "tidyverse, sf, janitor, here"
 },
 {
  "d": "2020-02-karamanis-2-lines",
  "m": "karamanis",
  "y": "2020",
  "n": 2,
  "t": "Lines",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/2-lines/2-lines.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/2-lines/2-lines.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/2-lines/2-lines.R",
  "l": "R",
  "p": "tidyverse, sf, janitor, here"
 },
 {
  "d": "2020-01-karamanis-1-points",
  "m": "karamanis",
  "y": "2020",
  "n": 1,
  "t": "Points",
  "s": "",
  "i": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/1-points/1-points.png",
  "c": "https://raw.githubusercontent.com/gkaramanis/30DayMapChallenge/main/2020/1-points/1-points.R",
  "g": "https://github.com/gkaramanis/30DayMapChallenge/blob/main/2020/1-points/1-points.R",
  "l": "R",
  "p": "tidyverse, readxl, janitor, scales, here"
 }
];
