window.GALLERY_SNAPSHOT = [
  {
    "d": "2025-30",
    "y": "2025",
    "n": 30,
    "t": "Makeover",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_30.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_30.R",
    "l": "R",
    "p": "metR, tidyverse, camcorder, sf, showtext, elevatr, MetBrewer, ggtext, glue, nrBrand, terra",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_30.R"
  },
  {
    "d": "2025-29",
    "y": "2025",
    "n": 29,
    "t": "Raster",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_29.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_29.R",
    "l": "R",
    "p": "tidyverse, ggtext, nrBrand, rnaturalearth, showtext, terra, elevatr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_29.R"
  },
  {
    "d": "2025-28",
    "y": "2025",
    "n": 28,
    "t": "Black",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_28.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_28.R",
    "l": "R",
    "p": "tidyverse, sf, showtext, ggtext, nrBrand, glue, rnaturalearth, ggfx",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_28.R"
  },
  {
    "d": "2025-27",
    "y": "2025",
    "n": 27,
    "t": "Boundaries",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_27.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_27.R",
    "l": "R",
    "p": "tidyverse, sf, showtext, ggtext, nrBrand, camcorder, glue",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_27.R"
  },
  {
    "d": "2025-26",
    "y": "2025",
    "n": 26,
    "t": "Transport",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_26.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_26.R",
    "l": "R",
    "p": "openrouteservice, tidyverse, osmdata, sf, showtext, nrBrand, ggtext, MetBrewer, camcorder, dplyr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_26.R"
  },
  {
    "d": "2025-25",
    "y": "2025",
    "n": 25,
    "t": "Hexagons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_25.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_25.R",
    "l": "R",
    "p": "ggplot2, dplyr, stringr, showtext, nrBrand, ggtext, geofacet, camcorder, glue, tibble, PrettyCols",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_25.R"
  },
  {
    "d": "2025-24",
    "y": "2025",
    "n": 24,
    "t": "Places and their names",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_24.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_24.R",
    "l": "R",
    "p": "tidyverse, sf, showtext, ggtext, nrBrand, camcorder, glue, MetBrewer",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_24.R"
  },
  {
    "d": "2025-23",
    "y": "2025",
    "n": 23,
    "t": "Process",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_23.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_23.R",
    "l": "R",
    "p": "camcorder",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_23.R"
  },
  {
    "d": "2025-22",
    "y": "2025",
    "n": 22,
    "t": "Natural Earth",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_22.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_22.R",
    "l": "R",
    "p": "geodata, ggplot2, dplyr, biscale, elevatr, sf, showtext, nrBrand, ggtext, cowplot",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_22.R"
  },
  {
    "d": "2025-21",
    "y": "2025",
    "n": 21,
    "t": "Icons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_21.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_21.R",
    "l": "R",
    "p": "gapminder, geofacet, tidyverse, ggforce, camcorder, glue, nrBrand, ggtext, scales, showtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_21.R"
  },
  {
    "d": "2025-20",
    "y": "2025",
    "n": 20,
    "t": "Water",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_20.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_20.R",
    "l": "R",
    "p": "tidyverse, camcorder, ggtext, osmdata, sf, sysfonts, showtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_20.R"
  },
  {
    "d": "2025-19",
    "y": "2025",
    "n": 19,
    "t": "Projections",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_19.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_19.R",
    "l": "R",
    "p": "gridmappr, tidyverse, sf, showtext, patchwork, nrBrand",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_19.R"
  },
  {
    "d": "2025-18",
    "y": "2025",
    "n": 18,
    "t": "Out of this World",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_18.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_18.R",
    "l": "R",
    "p": "rvest, tidyverse, sf, rnaturalearth, showtext, ggtext, ggfx, nrBrand, camcorder",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_18.R"
  },
  {
    "d": "2025-17",
    "y": "2025",
    "n": 17,
    "t": "New tool",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_17.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_17.R",
    "l": "R",
    "p": "gridmappr, tidyverse, sf, rnaturalearth, showtext, ggtext, nrBrand, camcorder, readxl, rcartocolor, glue, devtools",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_17.R"
  },
  {
    "d": "2025-16",
    "y": "2025",
    "n": 16,
    "t": "Cell",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_16.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_16.R",
    "l": "R",
    "p": "tidyverse, ggtext, nrBrand, showtext, ggforce, sf, elevatr, terra",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_16.R"
  },
  {
    "d": "2025-15",
    "y": "2025",
    "n": 15,
    "t": "Fire",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_15.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_15.R",
    "l": "R",
    "p": "tidyverse, camcorder, sf, showtext, ggfx, gganimate",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_15.R"
  },
  {
    "d": "2025-14",
    "y": "2025",
    "n": 14,
    "t": "OpenStreetMap",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_14.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_14.R",
    "l": "R",
    "p": "glue, tidyverse, camcorder, nrBrand, ggtext, osmdata, sf, sysfonts, showtext, tibble",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_14.R"
  },
  {
    "d": "2025-13",
    "y": "2025",
    "n": 13,
    "t": "10 minute map",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_13.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_13.R",
    "l": "R",
    "p": "tidyverse, sf, osrm, ggmap, showtext, glue, ggtext, ggspatial, camcorder, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_13.R"
  },
  {
    "d": "2025-12",
    "y": "2025",
    "n": 12,
    "t": "Map from 2125",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_12.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_12.R",
    "l": "R",
    "p": "tidyverse, sf, showtext, ggtext, ggfx, nrBrand",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_12.R"
  },
  {
    "d": "2025-11",
    "y": "2025",
    "n": 11,
    "t": "Minimal",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_11.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_11.R",
    "l": "R",
    "p": "gapminder, geofacet, tidyverse, ggforce, camcorder, glue, nrBrand, ggtext, showtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_11.R"
  },
  {
    "d": "2025-10",
    "y": "2025",
    "n": 10,
    "t": "Air",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_10.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_10.R",
    "l": "R",
    "p": "glue, tidyverse, camcorder, nrBrand, ggtext, openair, showtext, rnaturalearth, sf, ggnewscale",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_10.R"
  },
  {
    "d": "2025-09",
    "y": "2025",
    "n": 9,
    "t": "Analog",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_09.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2025",
    "l": "Hand-drawn",
    "p": ""
  },
  {
    "d": "2025-08",
    "y": "2025",
    "n": 8,
    "t": "Urban",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_08.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_08.R",
    "l": "R",
    "p": "glue, tidyverse, camcorder, nrBrand, patchwork, ggtext, sysfonts, showtext, tibble, sf, osmdata, dplyr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_08.R"
  },
  {
    "d": "2025-07",
    "y": "2025",
    "n": 7,
    "t": "Accessibility",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_07.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_07.R",
    "l": "R",
    "p": "tidyverse, rnaturalearth, patchwork, showtext, ggtext, nrBrand, camcorder, glue, colorspace, cowplot, colorblindr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_07.R"
  },
  {
    "d": "2025-06",
    "y": "2025",
    "n": 6,
    "t": "Dimensions",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_06.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_06.R",
    "l": "R",
    "p": "geodata, rayshader, ggplot2, tidyr, dplyr, viridis",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_06.R"
  },
  {
    "d": "2025-05",
    "y": "2025",
    "n": 5,
    "t": "Earth",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_05.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_05.R",
    "l": "R",
    "p": "tidyverse, rnaturalearth, sf, patchwork, glue, showtext, nrBrand, ggtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_05.R"
  },
  {
    "d": "2025-04",
    "y": "2025",
    "n": 4,
    "t": "My Data",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_04.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_04.R",
    "l": "R",
    "p": "tidyverse, gpx, sf, camcorder, ggtext, showtext, glue, osmdata",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_04.R"
  },
  {
    "d": "2025-03",
    "y": "2025",
    "n": 3,
    "t": "Polygons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_03.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_03.R",
    "l": "R",
    "p": "glue, sysfonts, showtext, osmdata, tibble, sf, dplyr, ggplot2, maprints, ggtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_03.R"
  },
  {
    "d": "2025-02",
    "y": "2025",
    "n": 2,
    "t": "Lines",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_02.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_02.R",
    "l": "R",
    "p": "sysfonts, showtext, osmdata, tibble, sf, maprints, ggplot2",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_02.R"
  },
  {
    "d": "2025-01",
    "y": "2025",
    "n": 1,
    "t": "Points",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/maps/day_01.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2025/scripts/day_01.R",
    "l": "R",
    "p": "tidyverse, showtext, camcorder, ggtext, nrBrand, glue, osmdata, sf, ggfx, tidytuesdayR",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2025/scripts/day_01.R"
  },
  {
    "d": "2024-06",
    "y": "2024",
    "n": 6,
    "t": "Raster",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2024/maps/day_06.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2024/scripts/day_06.R",
    "l": "R",
    "p": "tidyverse, showtext, ggtext, nrBrand, geofacet, glue, tidytuesdayR",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2024/scripts/day_06.R"
  },
  {
    "d": "2023-26",
    "y": "2023",
    "n": 26,
    "t": "Minimal",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/maps/day_26.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2023/scripts/day_26.R",
    "l": "R",
    "p": "tibble, dplyr, sf, rgeoboundaries, sysfonts, showtext, nrBrand, ggplot2, ggtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/scripts/day_26.R"
  },
  {
    "d": "2023-05",
    "y": "2023",
    "n": 5,
    "t": "Analog",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/maps/day_05.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2023/scripts/day_05.R",
    "l": "R",
    "p": "tidyverse, ggtext, sf, nrBrand, showtext, rgeoboundaries, elevatr, terra",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/scripts/day_05.R"
  },
  {
    "d": "2023-02",
    "y": "2023",
    "n": 2,
    "t": "Lines",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/maps/day_02.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2023/scripts/day_02.py",
    "l": "Python",
    "p": "ridge_map, matplotlib, numpy",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2023/scripts/day_02.py"
  },
  {
    "d": "2022-30",
    "y": "2022",
    "n": 30,
    "t": "Remix",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_30.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_30.R",
    "l": "R",
    "p": "leaflet, tidyverse, sf, mapview, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_30.R"
  },
  {
    "d": "2022-29",
    "y": "2022",
    "n": 29,
    "t": "Out of Comfort Zone",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_29.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_29.py",
    "l": "Python",
    "p": "geopandas, matplotlib, mpl_toolkits",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_29.py"
  },
  {
    "d": "2022-28",
    "y": "2022",
    "n": 28,
    "t": "3D",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_28.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_28.R",
    "l": "R",
    "p": "rayshader, elevatr, tidyverse, sf, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_28.R"
  },
  {
    "d": "2022-27",
    "y": "2022",
    "n": 27,
    "t": "Music",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_27.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_27.R",
    "l": "R",
    "p": "tidyverse, showtext, camcorder, ggforce, geofacet, ggtext, rcartocolor, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_27.R"
  },
  {
    "d": "2022-26",
    "y": "2022",
    "n": 26,
    "t": "Islands",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_26.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_26.R",
    "l": "R",
    "p": "tidyverse, sf, showtext, ggrepel, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_26.R"
  },
  {
    "d": "2022-25",
    "y": "2022",
    "n": 25,
    "t": "Two Colours",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_25.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_25.R",
    "l": "R",
    "p": "tidyverse, sf, biscale, cowplot, showtext, ons, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_25.R"
  },
  {
    "d": "2022-24",
    "y": "2022",
    "n": 24,
    "t": "Fantasy)",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_24.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_24.R",
    "l": "R",
    "p": "tidyverse, sf, showtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_24.R"
  },
  {
    "d": "2022-23",
    "y": "2022",
    "n": 23,
    "t": "Movement",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_23.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_23.R",
    "l": "R",
    "p": "tidyverse, ggmap, osmdata, rcartocolor, rStrava, gganimate",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_23.R"
  },
  {
    "d": "2022-22",
    "y": "2022",
    "n": 22,
    "t": "NULL",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_22.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_22.R",
    "l": "R",
    "p": "tidyverse, sf, showtext, ons, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_22.R"
  },
  {
    "d": "2022-21",
    "y": "2022",
    "n": 21,
    "t": "Kontur Population Data",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_21.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_21.R",
    "l": "R",
    "p": "scico, R.utils, tidyverse, sf, showtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_21.R"
  },
  {
    "d": "2022-20",
    "y": "2022",
    "n": 20,
    "t": "My Favourite ...",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_20.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_20.R",
    "l": "R",
    "p": "tidyverse, sf, rcartocolor, showtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_20.R"
  },
  {
    "d": "2022-19",
    "y": "2022",
    "n": 19,
    "t": "Globe",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_19.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_19.R",
    "l": "R",
    "p": "tidyverse",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_19.R"
  },
  {
    "d": "2022-18",
    "y": "2022",
    "n": 18,
    "t": "Blue",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_18.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_18.R",
    "l": "R",
    "p": "tanaka, elevatr, terra, PrettyCols",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_18.R"
  },
  {
    "d": "2022-17",
    "y": "2022",
    "n": 17,
    "t": "Without a Computer",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_17.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2022",
    "l": "Hand-drawn",
    "p": ""
  },
  {
    "d": "2022-16",
    "y": "2022",
    "n": 16,
    "t": "Minimal",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_16.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_16.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_16.R"
  },
  {
    "d": "2022-15",
    "y": "2022",
    "n": 15,
    "t": "Food / Drink",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_15.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_15.R",
    "l": "R",
    "p": "tidyverse, sf, cowplot, grid, nngeo, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_15.R"
  },
  {
    "d": "2022-14",
    "y": "2022",
    "n": 14,
    "t": "Hexagons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_14.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_14.R",
    "l": "R",
    "p": "tidyverse, geojsonio, usefunc, rcartocolor, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_14.R"
  },
  {
    "d": "2022-13",
    "y": "2022",
    "n": 13,
    "t": "5 Minutes",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_13.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_13.R",
    "l": "R",
    "p": "osrm, sf, tidyverse, ggmap, ggtext",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_13.R"
  },
  {
    "d": "2022-12",
    "y": "2022",
    "n": 12,
    "t": "Scale",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_12.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_12.R",
    "l": "R",
    "p": "tidyverse, sf, PrettyCols, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_12.R"
  },
  {
    "d": "2022-11",
    "y": "2022",
    "n": 11,
    "t": "Red",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_11.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_11.R",
    "l": "R",
    "p": "tidyverse, sf, osmdata, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_11.R"
  },
  {
    "d": "2022-10",
    "y": "2022",
    "n": 10,
    "t": "A Bad Map",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_10.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_10.R",
    "l": "R",
    "p": "tidyverse, sf, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_10.R"
  },
  {
    "d": "2022-09",
    "y": "2022",
    "n": 9,
    "t": "Space",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_09.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_09.R",
    "l": "R",
    "p": "tidyverse, ggforce, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_09.R"
  },
  {
    "d": "2022-08",
    "y": "2022",
    "n": 8,
    "t": "OpenStreetMap Data",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_08.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_08.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_08.R"
  },
  {
    "d": "2022-07",
    "y": "2022",
    "n": 7,
    "t": "Raster",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_07.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_07.R",
    "l": "R",
    "p": "tidyverse, sf, stars, PrettyCols, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_07.R"
  },
  {
    "d": "2022-06",
    "y": "2022",
    "n": 6,
    "t": "Network",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_06.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_06.R",
    "l": "R",
    "p": "tidyverse, sf, osmdata",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_06.R"
  },
  {
    "d": "2022-05",
    "y": "2022",
    "n": 5,
    "t": "Ukraine",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_05.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_05.R",
    "l": "R",
    "p": "tidyverse, sf, rnaturalearth",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_05.R"
  },
  {
    "d": "2022-04",
    "y": "2022",
    "n": 4,
    "t": "Green",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_04.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_04.R",
    "l": "R",
    "p": "tidyverse, PrettyCols, readr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_04.R"
  },
  {
    "d": "2022-03",
    "y": "2022",
    "n": 3,
    "t": "Polygons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_03.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_03.R",
    "l": "R",
    "p": "tidyverse, sf, tmap, viridis, rnaturalearth",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_03.R"
  },
  {
    "d": "2022-02",
    "y": "2022",
    "n": 2,
    "t": "Lines",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_02.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_02.R",
    "l": "R",
    "p": "tidyverse, sf, roughsf, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_02.R"
  },
  {
    "d": "2022-01",
    "y": "2022",
    "n": 1,
    "t": "Points",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/maps/day_01.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2022/scripts/day_01.R",
    "l": "R",
    "p": "tidyverse, sf, cowplot, grid, readr, ons",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2022/scripts/day_01.R"
  },
  {
    "d": "2021-30",
    "y": "2021",
    "n": 30,
    "t": "Metamapping",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_30.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_30.R",
    "l": "R",
    "p": "tidyverse, rcartocolor",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_30.R"
  },
  {
    "d": "2021-29",
    "y": "2021",
    "n": 29,
    "t": "Null",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_29.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_29.R",
    "l": "R",
    "p": "osrm, sf, tidyverse, ggmap, ragg",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_29.R"
  },
  {
    "d": "2021-28",
    "y": "2021",
    "n": 28,
    "t": "The Earth is not flat",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_28.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_28.R",
    "l": "R",
    "p": "rayshader, reshape2, raster, tidyverse, rgdal",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_28.R"
  },
  {
    "d": "2021-27",
    "y": "2021",
    "n": 27,
    "t": "Heatmap",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_27.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_27.R",
    "l": "R",
    "p": "ggplot2, sf, rcartocolor, dplyr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_27.R"
  },
  {
    "d": "2021-26",
    "y": "2021",
    "n": 26,
    "t": "Choropleth map",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_26.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_26.R",
    "l": "R",
    "p": "tidyverse, cowplot, showtext, ragg, biscale, sf",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_26.R"
  },
  {
    "d": "2021-25",
    "y": "2021",
    "n": 25,
    "t": "Interactive map",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_25.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_25.R",
    "l": "R",
    "p": "leaflet, htmlwidgets, sf, dplyr, MapColoring, CEoptim, rcartocolor",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_25.R"
  },
  {
    "d": "2021-24",
    "y": "2021",
    "n": 24,
    "t": "Historical map",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_24.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_24.R",
    "l": "R",
    "p": "sf, sp, ggplot2, rcartocolor, MapColoring, CEoptim, devtools",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_24.R"
  },
  {
    "d": "2021-23",
    "y": "2021",
    "n": 23,
    "t": "GHSL",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_23.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_23.R",
    "l": "R",
    "p": "raster, sp, leaflet, rcartocolor",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_23.R"
  },
  {
    "d": "2021-22",
    "y": "2021",
    "n": 22,
    "t": "Boundaries",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_22.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_22.R",
    "l": "R",
    "p": "sf, ggplot2, roughsf, dplyr",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_22.R"
  },
  {
    "d": "2021-21",
    "y": "2021",
    "n": 21,
    "t": "Elevation",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_21.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_21.R",
    "l": "R",
    "p": "tidyverse, rayshader, raster, rgdal, png",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_21.R"
  },
  {
    "d": "2021-20",
    "y": "2021",
    "n": 20,
    "t": "Movement",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_20.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_20.R",
    "l": "R",
    "p": "sf, ggplot2, dplyr, rcartocolor",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_20.R"
  },
  {
    "d": "2021-19",
    "y": "2021",
    "n": 19,
    "t": "Island(s)",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_19.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_19.R",
    "l": "R",
    "p": "sf, ggplot2, dplyr, magick, cowplot",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_19.R"
  },
  {
    "d": "2021-18",
    "y": "2021",
    "n": 18,
    "t": "Water",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_18.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_18.R",
    "l": "R",
    "p": "marmap, ggplot2",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_18.R"
  },
  {
    "d": "2021-17",
    "y": "2021",
    "n": 17,
    "t": "Land",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_17.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_17.R",
    "l": "R",
    "p": "sf, ggplot2, dplyr, pals",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_17.R"
  },
  {
    "d": "2021-16",
    "y": "2021",
    "n": 16,
    "t": "Urban/rural",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_16.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_16.R",
    "l": "R",
    "p": "sf, ggplot2, rcartocolor, cowplot, magick",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_16.R"
  },
  {
    "d": "2021-15",
    "y": "2021",
    "n": 15,
    "t": "Map without a computer",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_15.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2021",
    "l": "Hand-drawn",
    "p": ""
  },
  {
    "d": "2021-14",
    "y": "2021",
    "n": 14,
    "t": "Map with a new tool",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_14.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/tree/main/2021",
    "l": "Tableau",
    "p": ""
  },
  {
    "d": "2021-13",
    "y": "2021",
    "n": 13,
    "t": "Natural Earth",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_13.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_13.R",
    "l": "R",
    "p": "rnaturalearth, rnaturalearthdata, ggplot2, sf, ggspatial, rcartocolor",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_13.R"
  },
  {
    "d": "2021-12",
    "y": "2021",
    "n": 12,
    "t": "Population",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_12.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_12.R",
    "l": "R",
    "p": "sf, dplyr, readr, ggplot2, RColorBrewer, geofacet, cowplot, patchwork",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_12.R"
  },
  {
    "d": "2021-11",
    "y": "2021",
    "n": 11,
    "t": "3D",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_11.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_11.R",
    "l": "R",
    "p": "sf, dplyr, stringr, readr, ggplot2, cowplot, extrafont, magick, rayshader",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_11.R"
  },
  {
    "d": "2021-10",
    "y": "2021",
    "n": 10,
    "t": "Raster",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_10.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_10.R",
    "l": "R",
    "p": "elevatr, rayshader, sf, rgeoboundaries, tidyverse",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_10.R"
  },
  {
    "d": "2021-09",
    "y": "2021",
    "n": 9,
    "t": "Monochrome",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_09.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_09.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf, cowplot",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_09.R"
  },
  {
    "d": "2021-08",
    "y": "2021",
    "n": 8,
    "t": "Blue",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_08.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_08.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf, cowplot, ggmap, patchwork",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_08.R"
  },
  {
    "d": "2021-07",
    "y": "2021",
    "n": 7,
    "t": "Green",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_07.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_07.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf, cowplot, ggmap, patchwork",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_07.R"
  },
  {
    "d": "2021-06",
    "y": "2021",
    "n": 6,
    "t": "Red",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_06.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_06.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf, cowplot",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_06.R"
  },
  {
    "d": "2021-05",
    "y": "2021",
    "n": 5,
    "t": "OpenStreetMap",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_05.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_05.R",
    "l": "R",
    "p": "tidyverse, osmdata, sf, ggmap, cowplot",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_05.R"
  },
  {
    "d": "2021-04",
    "y": "2021",
    "n": 4,
    "t": "Hexagons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_04.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_04.R",
    "l": "R",
    "p": "tidyverse, viridis, ggplot2, stringr, sf, dplyr, readr, cowplot, extrafont, magick, hexbin",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_04.R"
  },
  {
    "d": "2021-03",
    "y": "2021",
    "n": 3,
    "t": "Polygons",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_03.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_03.R",
    "l": "R",
    "p": "sf, dplyr, stringr, readr, ggplot2, cowplot, extrafont, magick",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_03.R"
  },
  {
    "d": "2021-02",
    "y": "2021",
    "n": 2,
    "t": "Lines",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_02.png",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_02.R",
    "l": "R",
    "p": "sf, raster, dplyr, spData, spDataLarge, tmap, leaflet, ggplot2, maptools, sp",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_02.R"
  },
  {
    "d": "2021-01",
    "y": "2021",
    "n": 1,
    "t": "Points",
    "i": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/maps/day_01.jpg",
    "g": "https://github.com/nrennie/30DayMapChallenge/blob/main/2021/scripts/day_01.R",
    "l": "R",
    "p": "sf, dplyr, stringr, readr, ggplot2, cowplot, extrafont, magick",
    "c": "https://raw.githubusercontent.com/nrennie/30DayMapChallenge/main/2021/scripts/day_01.R"
  }
];
