/* Official #30DayMapChallenge daily themes, from tjukanovt/30DayMapChallenge includes/themes-YYYY.md. Index 0 is day 1. */
(function(root) {
  const THEMES = {
 "2020": [
  "Points",
  "Lines",
  "Polygons",
  "Hexagons",
  "Blue",
  "Red",
  "Green",
  "Yellow",
  "Monochrome",
  "Grid",
  "3D",
  "Map not made with GIS software",
  "Raster",
  "Climate change",
  "Connections",
  "Island(s)",
  "Historical map",
  "Landuse",
  "NULL",
  "Population",
  "Water",
  "Movement",
  "Boundaries",
  "Elevation",
  "COVID-19",
  "Map with a new tool",
  "Big or small data",
  "Non-geographic map",
  "Globe",
  "A map"
 ],
 "2021": [
  "Points",
  "Lines",
  "Polygons",
  "Hexagons",
  "Data challenge 1: OpenStreetMap",
  "Red",
  "Green",
  "Blue",
  "Monochrome",
  "Raster",
  "3D",
  "Population",
  "Data challenge 2: Natural Earth",
  "Map with a new tool",
  "Map made without using a computer",
  "Urban/rural",
  "Land",
  "Water",
  "Island(s)",
  "Movement",
  "Elevation",
  "Boundaries",
  "Data challenge 3: GHSL Global Human Settlement Layer",
  "Historical map",
  "Interactive map",
  "Choropleth map",
  "Heatmap",
  "The Earth is not flat",
  "NULL",
  "Metamapping day"
 ],
 "2022": [
  "Points",
  "Lines",
  "Polygons",
  "Colour Friday: Green",
  "Ukraine",
  "Network",
  "Raster",
  "Data: OpenStreetMap",
  "Space",
  "A bad map",
  "Colour Friday: Red",
  "Scale",
  "5 minute map",
  "Hexagons",
  "Food/drink",
  "Minimal",
  "A map without a computer",
  "Colour Friday: Blue",
  "Globe",
  "\"My favourite…\"",
  "Data: Kontur Population Dataset",
  "NULL",
  "Movement",
  "Fantasy",
  "Colour Friday: 2 colours",
  "Island(s)",
  "Music",
  "3D",
  "\"Out of my comfort zone\"",
  "Remix"
 ],
 "2023": [
  "Points",
  "Lines",
  "Polygons",
  "A bad map",
  "Analog map",
  "Asia",
  "Navigation",
  "Africa",
  "Hexagons",
  "North America",
  "Retro",
  "South America",
  "Choropleth",
  "Europe",
  "OpenStreetMap",
  "Oceania",
  "Flow",
  "Atmosphere",
  "5-minute map",
  "Outdoors",
  "Raster",
  "North is not always up",
  "3D",
  "Black & white",
  "Antarctica",
  "Minimal",
  "Dot",
  "Is this a chart or a map?",
  "Population",
  "\"My favorite..\""
 ],
 "2024": [
  "Points",
  "Lines",
  "Polygons",
  "Hexagons",
  "A journey",
  "Raster",
  "Vintage style",
  "Humanitarian Data Exchange (HDX)",
  "AI only",
  "Pen & paper",
  "Arctic",
  "Time and space",
  "A new tool",
  "A world map",
  "My data",
  "Choropleth",
  "Collaborative map",
  "3D",
  "Typography",
  "OpenStreetMap",
  "Conflict",
  "2 colours",
  "Memory",
  "Only circular shapes",
  "Heat",
  "Map projections",
  "Micromapping",
  "The blue planet",
  "Overture",
  "The final map"
 ],
 "2025": [
  "Points",
  "Lines",
  "Polygons",
  "Data challenge: My Data",
  "Earth",
  "Dimensions",
  "Accessibility",
  "Urban",
  "Analog",
  "Air",
  "Minimal map",
  "Map from 2125",
  "10 minute map",
  "Data challenge: OpenStreetMap",
  "Fire",
  "Cell",
  "A new tool",
  "Out of this world",
  "Projections",
  "Water",
  "Icons",
  "Data challenge: Natural Earth",
  "Process",
  "Places and their names",
  "Hexagons",
  "Transport",
  "Boundaries",
  "Black",
  "Raster",
  "Makeover"
 ]
};
  if (typeof module !== 'undefined') module.exports = THEMES;
  else root.MAP_THEMES = THEMES;
})(globalThis);
